export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <section className="flex h-screen items-center bg-auth-pages bg-cover bg-center">
      {children}
    </section>
  );
}
