export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function AboutLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <h1>About Layout</h1>
        {children}
      </body>
    </html>
  );
}
