const blog = {
  title: 'What is Food and Why is it Good for You?',
  sections: [
    {
      subheading: 'How is Food Made?',
      paragraphs: [
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam dolor quam, fermentum quis felis ac, placerat euismod turpis. Suspendisse quis placerat purus. Vestibulum eget rutrum nisl. Curabitur metus neque, molestie id varius hendrerit, scelerisque nec ex. Sed mattis mi velit, ac blandit purus scelerisque sit amet. Etiam dapibus porttitor ante, non ultricies est auctor sit amet. Nam finibus efficitur felis eu placerat. Phasellus iaculis, nisi vitae condimentum ultrices, ipsum lacus tristique augue, sed dictum ante felis vel dui. Aliquam eget purus turpis. Donec auctor diam ac massa sollicitudin pulvinar Pellentesque imperdiet lectus ac fringilla pellentesque. Curabitur erat mauris, placerat id diam sit amet, lacinia blandit tortor. Nulla gravida non ipsum eu sollicitudin. In hac habitasse platea dictumst. Phasellus id nisl sit amet urna dictum placerat. Donec vitae arcu interdum lorem efficitur auctor. Praesent bibendum, felis sodales mattis pellentesque, lorem leo vestibulum enim, at vestibulum leo ipsum vitae neque. Fusce consectetur tincidunt nunc, et elementum tellus ornare vel. Donec aliquet eros quis mi convallis faucibus. Nulla non ligula lectus. Donec non leo sollicitudin justo tempus tincidunt a ut diam. Curabitur laoreet odio vitae posuere porttitor. Aliquam elit elit, scelerisque non posuere quis, commodo a lorem.',
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam dolor quam, fermentum quis felis ac, placerat euismod turpis. Suspendisse quis placerat purus. Vestibulum eget rutrum nisl. Curabitur metus neque, molestie id varius hendrerit, scelerisque nec ex. Sed mattis mi velit, ac blandit purus scelerisque sit amet. Etiam dapibus porttitor ante, non ultricies est auctor sit amet. Nam finibus efficitur felis eu placerat. Phasellus iaculis, nisi vitae condimentum ultrices, ipsum lacus tristique augue, sed dictum ante felis vel dui. Aliquam eget purus turpis. Donec auctor diam ac massa sollicitudin pulvinar Pellentesque imperdiet lectus ac fringilla pellentesque. Curabitur erat mauris, placerat id diam sit amet, lacinia blandit tortor. Nulla gravida non ipsum eu sollicitudin. In hac habitasse platea dictumst. Phasellus id nisl sit amet urna dictum placerat. Donec vitae arcu interdum lorem efficitur auctor. Praesent bibendum, felis sodales mattis pellentesque, lorem leo vestibulum enim, at vestibulum leo ipsum vitae neque. Fusce consectetur tincidunt nunc, et elementum tellus ornare vel. Donec aliquet eros quis mi convallis faucibus. Nulla non ligula lectus. Donec non leo sollicitudin justo tempus tincidunt a ut diam. Curabitur laoreet odio vitae posuere porttitor. Aliquam elit elit, scelerisque non posuere quis, commodo a lorem.',
      ],
    },
  ],
};
export default blog;
